### ISSUE TITLE
Minimal length of search string should be restricted

### ISSUE THREAD

**Issue by deletescape** [dkhmelenko/TravisClient-Android#10]
When searching for repositories any string which has a length below 3 chars will fail with an internal server error. If this really is a bug and it should be fixed I can fix it myself and send a pull request.

Best wishes and thanks for the app
Deletescape

**Comment by dkhmelenko** [comment]
Unfortunately, I cannot do anything with Travis BE. So limiting to 3 chars should solve this issue.
PR is welcome, however, I have to warn you that current develop branch could be in a bit unstable condition, I'm improving app architecture. So don't worry, if something could not work, it will be fixed soon.

**Comment by deletescape** [comment]
I will make a fix in the evening and send you a PR.
