### ISSUE TITLE
Build matrix jobs show zero seconds duration

### ISSUE THREAD

**Issue by bkimminich** [dkhmelenko/TravisClient-Android#11]
![image](https://cloud.githubusercontent.com/assets/3531020/19206320/49946960-8ce8-11e6-8e64-37be66a03665.png)

Occured in `v.1.00.006`. Examples to reproduce:
* https://travis-ci.org/bkimminich/z85-cli
* https://travis-ci.org/bkimminich/juice-shop

Both are repos with a build matrix. The total execution time in the build view is correctly shown, just the individual execution times are zero.

**Comment by dkhmelenko** [comment]
Thanks for reporting. This issue requires a check, because before it was an issue on Travis BE, so responses for job had always duration as 0.

**Comment by dkhmelenko** [comment]
Job entitity doens't have a field `duration`. Parse the fields `started_at` and `finished_at` for calculation of the job duration.
