### ISSUE TITLE
Add APK to Github releases?

### ISSUE THREAD

**Issue by IzzySoft** [dkhmelenko/TravisClient-Android#18]
Would you mind adding the `.apk` build to the corresponding `releases/` here at Github – for folks not using Google Play?

**Comment by dkhmelenko** [comment]
Good point. Will be done soon

**Comment by IzzySoft** [comment]
Thanks a lot! Looking forward to it :)

**Comment by IzzySoft** [comment]
Thanks! Though I rather had [the releases page](https://github.com/dkhmelenko/TravisClient-Android/releases) in mind (as [described here](https://help.github.com/articles/creating-releases/)) :) But if it's easier to automate this way, the purpose is met as well.

**Comment by dkhmelenko** [comment]
@IzzySoft fixed that!

**Comment by IzzySoft** [comment]
Cool! Thanks! Fixed your app's Metadata so my auto-updater can grap new releases automatically then :) Oops: See [here](https://apt.izzysoft.de/fdroid/index/apk/com.khmelenko.lab.travisclient) for what I'm talking about. And feel free to refer your users there: the repo can be used with the F-Droid client.
