### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by eygraber** [dkhmelenko/TravisClient-Android#9]
When I try to view a build log, I only see a message that says "no access token supplied"

**Comment by dkhmelenko** [comment]
@eygraber Does it happen with public or private repository? Or for both?

**Comment by eygraber** [comment]
So far I've only tried with private repositories. I did notice that if I click a link from GitHub and open it with the app, it sometimes works.

**Comment by dkhmelenko** [comment]
I will check everything, but I remember there was an issue with that.

**Comment by dkhmelenko** [comment]
@eygraber how did you see this error - in view on in Toast?
